# GreatCrafts config


# Setting to unlock custom crafts
#   never - Never automatically unlocks custom recipes
#   have-each - Automatically unlocks custom recipes if the player has each of the required ingredients
#                 To fix O(scary) stuff, you'll only need 1 of each item, e.g. if the requirement is 2 diamonds and
#                 2 emeralds, the player only needs 1 diamond and 1 emerald.
#   have-one - Automatically unlocks custom recipes if the player has at least one of the required ingredients
#   always - Automatically unlocks all custom recipes immediately
automatically-unlock-recipes: never


# You can change the messages used by the plugin here.
# The general format is
#   message-thing:
#   - "Line 1"
#   - "Line 2"
#   - "..."
# Use § or & for color codes.
language-settings:

  # When an exact match is missed in a stacked items craft, usually because it's mirrored
  # Placeholders: %recipekey% = the recipe key
  stackedItemsErrorMissedExactMatch:
  - "§cThe recipe doesn't exactly match!"
  - "§3You probably mirrored the recipe."
  - "§3Check §f/viewrecipe %recipekey% §3to make the craft."

  # When you don't have enough items to make the stacked items craft.
  # Placeholders: %recipekey% = the recipe key
  stackedItemsErrorNotEnoughItems:
  - "§cYou don't have enough items in the crafting table!"
  - "§3This is a special §bstacked items §3recipe."
  - "§3Check §f/viewrecipe %recipekey% §3to make the craft."

