name: GreatCrafts
version: "${project.version}"
main: io.github.greatericontop.greatcrafts.GreatCrafts
api-version: 1.19
authors: [greateric]

commands:
  greatcrafts:
    description: Main command
    usage: "§c/greatcrafts"
  recipes:
    description: View all recipes
    usage: "§c/recipes <optional search query>"
    permission: greatcrafts.viewrecipes
  viewrecipe:
    description: View a recipe
    usage: "§c/viewrecipe <namespace:name>"
    permission: greatcrafts.viewrecipes
  addrecipe:
    description: Add a recipe
    usage: "§c/addrecipe <namespace:name>"
    permission: greatcrafts.modifyrecipes
  editrecipe:
    description: Edit a recipe
    usage: "§c/editrecipe <namespace:name>"
    permission: greatcrafts.modifyrecipes
  deleterecipe:
    description: Delete a recipe
    usage: "§c/deleterecipe <namespace:name>"
    permission: greatcrafts.modifyrecipes
  reloadrecipes:
    description: Reload recipes
    usage: "§c/reloadrecipes"
    permission: greatcrafts.modifyrecipes
  greatcraftsutil:
    description: Random utility commands for GreatCrafts
    usage: "§c/greatcraftsutil [duplicaterecipe <source> <target>]"
    permission: greatcrafts.greatcraftsutil
    aliases: [gcutil]

permissions:
  greatcrafts.viewrecipes:
    description: Allows viewing recipes
    default: true
  greatcrafts.modifyrecipes:
    description: Allows modifying recipes
    default: op
  greatcrafts.greatcraftsutil:
    description: Allows using /greatcraftsutil
    default: op