name: GreatCrafts
version: "${project.version}"
main: io.github.greatericontop.greatcrafts.GreatCrafts
api-version: 1.19
authors: [greateric]

commands:
  recipes:
    description: View recipes
    usage: "§c/recipes"
    permission: greatcrafts.viewrecipes
  addrecipe:
    description: Add a recipe
    usage: "§c/addrecipe <namespace:name>"
    permission: greatcrafts.modifyrecipes
  editrecipe:
    description: Edit a recipe
    usage: "§c/editrecipe <namespace:name>"
    permission: greatcrafts.modifyrecipes
  reloadrecipes:
    description: Reload recipes
    usage: "§c/reloadrecipes"
    permission: greatcrafts.modifyrecipes

permissions:
  greatcrafts.viewrecipes:
    description: Allows viewing recipes
    default: true
  greatcrafts.modifyrecipes:
    description: Allows modifying recipes
    default: op