name: CustomCraftingCreator
version: "${project.version}"
main: io.github.greatericontop.customcraftingcreator.CustomCraftingCreator
api-version: 1.19
authors: [greatericontop]

commands:
  addrecipe:
    description: Add a recipe
    usage: "§c/addrecipe <namespace:name>"
    permission: customcraftingcreator.modifyrecipes
  editrecipe:
    description: Edit a recipe
    usage: "§c/editrecipe <namespace:name>"
    permission: customcraftingcreator.modifyrecipes
  reloadrecipes:
    description: Reload recipes
    usage: "§c/reloadrecipes"
    permission: customcraftingcreator.modifyrecipes

permissions:
  customcraftingcreator.viewrecipes:
    description: Allows viewing recipes
    default: true
  customcraftingcreator.modifyrecipes:
    description: Allows modifying recipes
    default: op